version: '3.8'

services:
  app:
    image: django
    build: ./django
    command: bash -cx "
      python manage.py migrate --no-input &&
      gunicorn --bind 0.0.0.0:8000 project.wsgi"
    restart: always
    volumes:
      - ./django/:/app/
      - static_volume:/app/staticfiles
    expose:
      - 8000
    env_file:
      - .env/.env.prod
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env/.env.prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1s
      timeout: 60s
      retries: 5
      start_period: 80s
  server:
    image: nginx
    build: ./nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - app

volumes:
  postgres_data:
  static_volume:
