services:
  - type: web
    plan: free
    name: view-and-review
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    repo: https://github.com/GEI-WP/view-and-review
    region: frankfurt
    branch: main
    rootDir: django
    healthCheckPath: /health
    envVars:
    - key: SECRET_KEY
      generateValue: true
    - key: DATABASE_URL
      fromDatabase:
        name: view-and-review-db
        property: connectionString   
    envVarGroups:
    - name: view-and-review

databases:
  - name: view-and-review-db
    region: frankfurt
    plan: free
    databaseName: viewandreview
    postgresMajorVersion: 15