services:
  - type: web
    plan: free
    name: view-and-review
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    repo: https://github.com/GEI-WP/view-and-review
    region: frankfurt
    branch: main
    rootDir: django
    healthCheckPath: /
    envVars:
      - key: DEBUG
        value: 0
      - key: ALLOWED_HOSTS
        value: localhost 127.0.0.1 view-and-review.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: view-and-review-db
          property: connectionString   

      - key: DJANGO_SETTINGS_MODULE
        value: project.settings.deps

databases:
  - name: view-and-review-db
    region: frankfurt
    plan: free
    databaseName: viewandreview
    postgresMajorVersion: 15