version: '3.4'

services:
  web:
    image: django
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn --bind 0.0.0.0:8000 project.wsgi
    volumes:
      - .:/workspace
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

volumes:
  postgres_data: